name: Bug Report
description: Report a bug encountered with Scylla Operator
labels: kind/bug
body:
- type: textarea
  id: problem
  attributes:
    label: What happened?
    description: |
      Please provide as much info as possible. Ensuring all details are shared in your report will help us address your bug in a timely manner.
  validations:
    required: true

- type: textarea
  id: expected
  attributes:
    label: What did you expect to happen?
  validations:
    required: true

- type: textarea
  id: repro
  attributes:
    label: How can we reproduce it (as minimally and precisely as possible)?
  validations:
    required: true

- type: textarea
  id: operatorVersion
  attributes:
    label: Scylla Operator version
  validations:
    required: true

- type: textarea
  id: kubernetesPlatform
  attributes:
    label: Kubernetes platform name and version
    value: |
      <details>
      ```console
      $ kubectl version
      # paste output here
      ```

      Kubernetes platform info:
      </details>
  validations:
    required: true

- type: textarea
  id: must-gather
  attributes:
    label: |
      Please attach the must-gather archive.
    description: |
      The must-gather archive is a **mandatory** part of every bug report.
      See https://operator.docs.scylladb.com/stable/support/must-gather.html to learn how you can collect it.
      Do not edit the collected must-gather.
      
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: true

- type: textarea
  id: additional
  attributes:
    label: Anything else we need to know?
