name: CI Flake
description: Report CI jobs that flaked
labels: kind/flake
body:
- type: textarea
  id: jobref
  attributes:
    label: Link to the job that flaked.
  validations:
    required: true

- type: textarea
  id: details
  attributes:
    label: Snippet of what failed.
    description: Insert a short snippet of what failed to have a quick preview (stack trace) and something to track even if logs are gone.
  validations:
    required: true
